apiVersion: v1
kind: ConfigMap
metadata:
  name: vp-configmap-default
data:
  BASE_PATH: "{{ tpl .Values.paths.base . }}"
  DATA_PATH: "{{ tpl .Values.paths.data . }}"
  CONFIGURATION_VERSION_FILE: "{{ tpl .Values.paths.config . }}/config.version"
  DEFAULTROUTING_ALLOWEDCONTRACTS: "{{ .Values.defaultRouting.allowedContracts | join "," }}"
  HEADERS_REG_EXP_REQUESTHEADERSTOREMOVE: "(?i){{ .Values.headers.requestHeadersToRemove | join "|" }}"
  HSA_FILES: "{{ tpl .Values.paths.config . }}/hsacachecomplementary.xml,{{ tpl .Values.paths.hsafiles . }}/hsacache.xml"
  IP_WHITELIST: "{{ .Values.ipWhiteList_vp.prefixes | join "," }}"
  HTTP_FORWARDED_HEADER_AUTH_CERT: "{{ .Values.headers.forwardedHeaderAuthCert }}"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "{{ .Values.management.endpointsWebExposureInclude | join "," }}"
  MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: "{{ .Values.management.endpointPrometheusEnabled }}"
  MEMORY_LOGGER_PERIOD_SECONDS: "{{ .Values.memoryLoggerPeriodSeconds }}"
  PRODUCER_HTTP_KEEPALIVE: "{{ .Values.producer.httpKeepalive }}"
  PRODUCER_HTTP_WORKERS: "{{ .Values.producer.httpWorkers }}"
  PRODUCER_HTTPS_KEEPALIVE: "{{ .Values.producer.httpsKeepalive }}"
  PRODUCER_HTTPS_WORKERS: "{{ .Values.producer.httpsWorkers }}"
  PROPAGATE_CORRELATION_ID_FOR_HTTPS: "{{ .Values.propagateCorrelationIdForHttps }}"
  SENDER_ID_ALLOWED_LIST: "{{ .Values.senderIdAllowedList | join "," }}"
  SERVER_FORWARDHEADERSSTRATEGY: "{{ .Values.server.forwardHeadersStrategy }}"
  SERVER_PORT: "{{ .Values.server.port }}"
  SERVER_UNDERTOW_ACCESSLOG_DIR: "{{ tpl .Values.server.undertow.accesslogDir . }}"
  SERVER_UNDERTOW_ACCESSLOG_ENABLED: "{{ .Values.server.undertow.accesslogEnabled }}"
  SERVER_UNDERTOW_ACCESSLOG_PATTERN: "{{ .Values.server.undertow.accesslogPattern }}"
  SERVER_UNDERTOW_ACCESSLOG_PREFIX: "{{ .Values.server.undertow.accesslogPrefix }}"
  SERVER_UNDERTOW_ACCESSLOG_ROTATE: "{{ .Values.server.undertow.accesslogRotate }}"
  SERVER_UNDERTOW_ACCESSLOG_SUFFIX: "{{ .Values.server.undertow.accesslogSuffix }}"
  TAKCACHE_ENDPOINT_ADDRESS: "{{ .Values.takcache.endpointAddress }}"
  TAKCACHE_PERSISTENT_FILE_NAME: "{{ tpl .Values.takcache.persistentFileName . }}"
  THROW_VP013_WHEN_ORIGINALCONSUMER_NOT_ALLOWED: "{{ .Values.throwVp013WhenOriginalconsumerNotAllowed }}"
  TIMEOUT_JSON_FILE: "{{ tpl .Values.paths.config . }}/timeoutconfig.json"
  TIMEOUT_JSON_FILE_DEFAULT_TJANSTEKONTRAKT_NAME: "{{ .Values.timeoutJsonFileDefaultTjanstekontraktName }}"
  VAGVALROUTER_DEFAULT_ROUTING_ADDRESS_DELIMITER: "{{ .Values.vagvalrouterDefaultRoutingAddressDelimiter }}"
  MESSAGE_LOGGER_METHOD: "{{ .Values.messageLoggerMethod }}"
  VP_HSA_RESET_CACHE_URL: "{{ .Values.skltp.urls.hsaResetCache }}"
  VP_HTTP_ROUTE_URL: "{{ .Values.skltp.urls.httpRoute }}"
  VP_HTTPS_ROUTE_URL: "{{ .Values.skltp.urls.httpsRoute }}"
  VP_INSTANCE_ID: "{{ .Values.skltp.instanceId }}"
  VP_INSTANCE_NAME: "{{ .Values.skltp.instanceName }}"
  VP_MAX_RECEIVE_LENGTH: "{{ .Values.skltp.maxReceiveLength }}"
  VP_RESET_CACHE_URL: "{{ .Values.skltp.urls.resetCache }}"
  VP_STATUS_URL: "{{ .Values.skltp.urls.status }}"
  VP_USE_ROUTING_HISTORY: "{{ .Values.skltp.useRoutingHistory }}"
  WSDL_JSON_FILE: "{{ tpl .Values.paths.config . }}/wsdlconfig.json"
  WSDLFILES_DIRECTORY: "{{ tpl .Values.paths.base . }}/wsdl/"
  JAVA_OPTS: >-
              -Dlog4j2.formatMsgNoLookups={{ .Values.javaOpts.systemProperties.log4j2FormatMsgNoLookups }}
              -Dfile.encoding={{ .Values.javaOpts.systemProperties.fileEncoding }}
              -Duser.country={{ .Values.javaOpts.systemProperties.userCountry }}
              -Duser.language={{ .Values.javaOpts.systemProperties.userLanguage }}
              -Dspring.profiles.active={{ .Values.javaOpts.systemProperties.springProfilesActive }}
              -Xms{{ .Values.javaOpts.jvm.minHeap }}
              -Xmx{{ .Values.javaOpts.jvm.maxHeap }}
              -XX:MaxRAMPercentage={{ .Values.javaOpts.jvm.maxRamPercentage }}
              -Dlog4j.configurationFile=file://{{ tpl .Values.paths.config . }}/log4j2.xml
              {{- if .Values.javaOpts.jmx.enabled }}
              -Dcom.sun.management.jmxremote
              -Dcom.sun.management.jmxremote.port={{ .Values.javaOpts.jmx.port }}
              -Dcom.sun.management.jmxremote.rmi.port={{ .Values.javaOpts.jmx.port }}
              -Dcom.sun.management.jmxremote.local.only={{ .Values.javaOpts.jmx.localOnly }}
              -Dcom.sun.management.jmxremote.authenticate={{ .Values.javaOpts.jmx.authenticate }}
              -Dcom.sun.management.jmxremote.ssl={{ .Values.javaOpts.jmx.ssl }}
              {{- end }}

{{- range .Values.tls.bundles }}
  SPRING_SSL_BUNDLE_PEM_{{ .name | upper }}_KEYSTORE_CERTIFICATE: "{{ tpl $.Values.paths.certs $ }}/{{ .name }}-keystore/tls.crt"
  SPRING_SSL_BUNDLE_PEM_{{ .name | upper }}_KEYSTORE_PRIVATEKEY: "{{ tpl $.Values.paths.certs $ }}/{{ .name }}-keystore/tls.key"
  SPRING_SSL_BUNDLE_PEM_{{ .name | upper }}_TRUSTSTORE_CERTIFICATE: "{{ tpl $.Values.paths.certs $ }}/{{ .name }}-truststore/ca.crt"
{{- end }}
{{- with .Values.tls.defaultConfig }}
  VP_TLS_DEFAULTCONFIG_NAME: "{{ .name }}"
  VP_TLS_DEFAULTCONFIG_BUNDLE: "{{ .bundle }}"
  {{- if .protocolsInclude }}
  VP_TLS_DEFAULTCONFIG_PROTOCOLSINCLUDE: "{{ join "," .protocolsInclude }}"
  {{- end }}
  {{- if .protocolsExclude }}
  VP_TLS_DEFAULTCONFIG_PROTOCOLSEXCLUDE: "{{ join "," .protocolsExclude }}"
  {{- end }}
  {{- if .cipherSuitesInclude }}
  VP_TLS_DEFAULTCONFIG_CIPHERSUITESINCLUDE: "{{ join "," .cipherSuitesInclude }}"
  {{- end }}
  {{- if .cipherSuitesExclude }}
  VP_TLS_DEFAULTCONFIG_CIPHERSUITESEXCLUDE: "{{ join "," .cipherSuitesExclude }}"
  {{- end }}
{{- end }}
{{- range $index, $override := .Values.tls.overrides }}
  VP_TLS_OVERRIDES_{{ $index }}_NAME: "{{ $override.name }}"
  VP_TLS_OVERRIDES_{{ $index }}_BUNDLE: "{{ $override.bundle }}"
  {{- if $override.match.domainName }}
  VP_TLS_OVERRIDES_{{ $index }}_MATCH_DOMAINNAME: "{{ $override.match.domainName }}"
  {{- end }}
  {{- if $override.match.domainSuffix }}
  VP_TLS_OVERRIDES_{{ $index }}_MATCH_DOMAINSUFFIX: "{{ $override.match.domainSuffix }}"
  {{- end }}
  {{- if $override.match.port }}
  VP_TLS_OVERRIDES_{{ $index }}_MATCH_PORT: "{{ $override.match.port }}"
  {{- end }}
  {{- if $override.protocolsInclude }}
  VP_TLS_OVERRIDES_{{ $index }}_PROTOCOLSINCLUDE: "{{ join "," $override.protocolsInclude }}"
  {{- end }}
  {{- if $override.protocolsExclude }}
  VP_TLS_OVERRIDES_{{ $index }}_PROTOCOLSEXCLUDE: "{{ join "," $override.protocolsExclude }}"
  {{- end }}
  {{- if $override.cipherSuitesInclude }}
  VP_TLS_OVERRIDES_{{ $index }}_CIPHERSUITESINCLUDE: "{{ join "," $override.cipherSuitesInclude }}"
  {{- end }}
  {{- if $override.cipherSuitesExclude }}
  VP_TLS_OVERRIDES_{{ $index }}_CIPHERSUITESEXCLUDE: "{{ join "," $override.cipherSuitesExclude }}"
  {{- end }}
{{- end }}
