apiVersion: v1
kind: ConfigMap
metadata:
  name: vp-hsacache-configmap-default
data:
  HSA_SYMLINK_FILE: "{{ tpl .Values.paths.hsafiles . }}/hsacache.xml"
  HSA_FILES_DIR: "{{ tpl .Values.paths.hsafiles . }}"
  HSA_FILE_NAME: "{{ .Values.hsacache.fileName }}"
  HSA_FILE_URL: "{{ .Values.hsacache.fileUrl }}"

  HSA_CA_CERT: "{{ .Values.hsacache.caCert }}"
  HSA_TLS_CERT: "{{ .Values.hsacache.tlsCert }}"
  HSA_TLS_KEY: "{{ .Values.hsacache.tlsKey }}"

  HSA_RESET_POD_NAMESPACE: "{{ $.Release.Namespace }}"
  HSA_RESET_LABEL_SELECTOR: "{{ .Values.hsacache.resetLabelSelector }}"
  HSA_RESET_URL_FORMAT: "{{ .Values.hsacache.resetUrlFormat }}"

  HSA_FILE_ALLOWABLE_DIFF: "{{ .Values.hsacache.fileAllowableDiff }}"
  HSA_SEND_ALERT_MAIL: "{{ .Values.hsacache.sendAlertMail }}"
