apiVersion: v1
kind: ConfigMap
metadata:
    name: vp-config-files
data:
    hsacachecomplementary.xml: |
        <?xml version="1.0" encoding="UTF-8"?>
        <FileGetHsaUnitsResponse xmlns="urn:riv:hsa:HsaWsResponder:3">
        <startDate>2013-03-15T15:38:42.597+01:00</startDate>
        <endDate>2013-03-15T15:38:45.721+01:00</endDate>
        <hsaUnits>
        <hsaUnit>
        <hsaIdentity>SE</hsaIdentity>
        <DN>c=SE</DN>
        <name>Sverige</name>
        </hsaUnit>
        </hsaUnits>
        </FileGetHsaUnitsResponse>
    log4j2.xml: |
        <Configuration status="WARN" monitorInterval="30">

        <Appenders>
        <Console name="Console" target="SYSTEM_OUT">
          <EcsLayout/>
        </Console>
        </Appenders>

        <Loggers>
          {{- range .Values.log4j.loggers }}
          <AsyncLogger name="{{ .name }}" level="{{ .level }}"/>
          {{- end }}
        
          <AsyncRoot level="{{ .Values.log4j.rootLoggerLevel }}">
            <AppenderRef ref="Console"/>
          </AsyncRoot>
        </Loggers>
        </Configuration>
    timeoutconfig.json: |
        {{ toJson .Values.timeoutConfig }}
    wsdlconfig.json: |
        {{ toJson .Values.wsdlConfig }}
