apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-hsa-cache
spec:
  schedule: "{{ .Values.hsaContainer.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: serviceaccount-vp-cron
          volumes:
            - name: cert-volume
              secret:
                secretName: {{ .Values.hsaContainer.certSecret }}
            - name: trust-volume
              secret:
                secretName: {{ .Values.hsaContainer.trustSecret }}
          containers:
            - name: {{ .Values.hsaContainer.image.name }}
              image: "{{ .Values.repository }}{{ .Values.hsaContainer.image.name }}:{{ .Values.hsaContainer.image.tag }}"
              imagePullPolicy: Always
              envFrom:
                {{- range $.Values.environment.variables.config_maps }}
                - configMapRef:
                    name: {{ . }}
                {{- end }}
                {{- range $.Values.environment.variables.secrets }}
                - secretRef:
                    name: {{ . }}
                {{- end }}
              volumeMounts:
                - name: cert-volume
                  mountPath: /opt/cert/tls.crt
                  subPath: tls.crt
                - name: cert-volume
                  mountPath: /opt/cert/tls.key
                  subPath: tls.key
                - name: trust-volume
                  mountPath: /opt/cert/ca.crt
                  subPath: ca.crt
              command:
                - /bin/bash
                - -c
                - date; sleep 3600
          imagePullSecrets:
            - name: regcred

          restartPolicy: OnFailure