{{- if .Values.ingress.enabled -}}
{{- $fullName := include "vp_services.fullname" . -}}

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}-direct
  labels:
    {{- include "vp_services.labels" . | nindent 4 }}
spec:
  routes:
    - kind: Rule
      match: "Host(`{{ .Values.ingressroute.bksVpHostName }}`) && PathPrefix(`/vp`)"
      middlewares:
        - name: pass-client-cert
        - name: vp-direct-ipwhitelist
      services:
        - kind: Service
          name: vp
          port: 8080
          scheme: http

  tls:
    secretName: {{ .Values.ingress.tls.secret.name }}
    options:
      name: mtls-option
{{- end }}