{{- if .Values.ingress.enabled -}}
{{- $fullName := include "vp_services.fullname" . -}}
{{- $hostName := include "vp_services.hostname" . -}}

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "vp_services.labels" . | nindent 4 }}
spec:
  routes:
    - kind: Rule
      match: "Host(`{{ $hostName }}`) && PathPrefix(`/vp`)"
      middlewares:
        - name: pass-client-cert
      services:
        - kind: Service
          name: vp
          port: 8080
          scheme: http
  tls:
    secretName: {{ .Values.ingress.tls.secret.name }}
    options:
      name: mtls-option

{{- end }}
