{{- if .Values.ingress.enabled -}}
{{- $fullName := include "vp_services.fullname" . -}}

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "vp_services.labels" . | nindent 4 }}
spec:
  routes:
    - kind: Rule
      match: "Host(`{{ .Values.ingressroute.esbHostName }}`) && PathPrefix(`/vp`)"
      middlewares:
        - name: pass-client-cert
      services:
        - kind: Service
          name: vp
          port: 8080
          scheme: http
{{- end }}
