apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vp-data-pvc
  namespace: ntjp-dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: basic-csi