apiVersion: v1
kind: Service
metadata:
  name: headless-vp
spec:
  clusterIP: None
  ports:
    - name: port-1
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: {{ .Values.app.vp.name }}
