apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Chart.Name }}
  name: {{.Chart.Name }}-direct-ipwhitelist
spec:
  ipWhiteList:
    sourceRange:
      - 10.6.3.0/24 # Orange-VPN
      - 185.144.144.144/28 # NMT-VPN