apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Chart.Name }}
  name: vp-direct-ipwhitelist
spec:
  ipWhiteList: {{ .Values.ipWhiteList_direct | toYaml | nindent 8 }}

---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Chart.Name }}
  name: vp-liveness-ipwhitelist
spec:
  ipWhiteList: {{ .Values.ipWhiteList_liveness | toYaml | nindent 8 }}

---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Chart.Name }}
  name: vp-http-ipwhitelist
spec:
  ipWhiteList: {{ .Values.ipWhiteList_http | toYaml | nindent 8 }}