CREATE TABLE LOGMANAGER_IMPORT_TB (ID VARCHAR(32), VALUE VARCHAR(128), CONSTRAINT LOGMANAGER_IMPORT_PK PRIMARY KEY (ID));
CREATE TABLE LOGQUEUE-CONSUMER_IMPORT_TB (ID VARCHAR(32), VALUE VARCHAR(128), CONSTRAINT LOGQUEUE-CONSUMER_IMPORT_PK PRIMARY KEY (ID));
