pipeline {
    agent any
    environment{
        JDK_PATH = tool name: 'Java 8_152'
        JAVA_HOME = "${JDK_PATH}"
        MAVEN_IMAGE = 'maven:3.6-jdk-8'
        SCANNER_HOME = tool name: 'SonarScanner 4.5'
    }

    stages {
        stage('Build') {
            agent {
                docker {
                    image "${MAVEN_IMAGE}"
                    args "-v ${JDK_PATH}:${JDK_PATH}"
                    reuseNode true
                }
            }
            steps {
                echo 'Starting Build stage...'
                configFileProvider([configFile(fileId: "${params.CONFIG_FILE_ID}", variable: 'MAVEN_SETTINGS')]) {
                    sh 'pwd'
                    echo 'Compiling, testing and building...'
                    sh 'mvn --global-settings ${MAVEN_SETTINGS} -P test-coverage,leak clean install'
                }
            }     
        }
        stage('SonarScanner'){
            steps {
                withCredentials([string(credentialsId: "${params.SONAR_TOKENID}", variable: "SONARTOKEN" )]) {
                    withSonarQubeEnv("${params.SONAR_ENV}") {
                        sh """${SCANNER_HOME}/bin/sonar-scanner \
                                    -Dsonar.projectKey=${params.SONAR_PROJECTKEY} \
                                    -Dsonar.login="${SONARTOKEN}" \
                                    -Dsonar.java.binaries=${params.SONAR_JAVA_BINARIES} \
                                    -Dsonar.coverage.jacoco.xmlReportPaths=${params.SONAR_JACOCO_REPORTS} \
                                    -Dsonar.test.inclusions=${params.SONAR_TEST_INCLUSIONS} \
                                    -Dsonar.sourceEncoding=UTF-8
                            """
                    }
                }
            }
        }
    }

    post {
        always {
            echo 'Starting results handling...'
            junit '**/target/surefire-reports/TEST-*.xml'
            jacoco()
            archiveArtifacts '**/target/*.jar'
        }

        unsuccessful {
            echo 'Build unsuccessful'
            emailext attachLog: true, 
                subject: "Build failed in Jenkins: ${JOB_NAME}#${BUILD_NUMBER}", 
                body: "See ${BUILD_URL} for details.",
                to: "${params.EMAIL_RECIPIENTS}"
        }

        changed {
            script {
                if ("${currentBuild.currentResult}" == 'SUCCESS') {
                    echo "Current build successful, previous build was unsuccessful"
                    emailext attachLog: true, 
                        subject: "${JOB_NAME} back to stable", 
                        body: "See ${BUILD_URL} for details.",
                        to: "${params.EMAIL_RECIPIENTS}"        
                }
            }
        }

        cleanup {
            echo 'Cleaning workspace...'
            cleanWs()
        }
    }
}
