<?xml version="1.0" encoding="UTF-8"?>
<!--
 * Copyright 2009 Sjukvardsradgivningen
 *
 *   This library is free software; you can redistribute it and/or modify
 *   it under the terms of version 2.1 of the GNU Lesser General Public

 *   License as published by the Free Software Foundation.
 *
 *   This library is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the

 *   GNU Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public
 *   License along with this library; if not, write to the
 *   Free Software Foundation, Inc., 59 Temple Place, Suite 330,

 *   Boston, MA 02111-1307  USA
 -->

<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:tns="urn:skl:tp:vagvalsinfo:v2" targetNamespace="urn:skl:tp:vagvalsinfo:v2">
	<wsdl:import namespace="urn:skl:tp:vagvalsinfo:v2" location="vagvalsinfo-sokvagvalsinfo-2.0.wsdl"/>
	<wsdl:service name="SokVagvalsServiceSoap11LitDocService">
		<wsdl:port name="SokVagvalsSoap11LitDocPort" binding="tns:SokVagvalsInfoInterfaceSoap11DocLitBinding">
			<soap:address location="http://tempuri.org/"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>